v2.25_reference

diff --git a/reference/grep/tests/long-pattern-perf b/reference/grep/tests/long-pattern-perf
--- a/reference/grep/tests/long-pattern-perf
+++ b/reference/grep/tests/long-pattern-perf
@@ -1,7 +1,7 @@
 #!/bin/sh
 # grep-2.21 would incur a 100x penalty for 10x increase in regexp length
 
-# Copyright 2015 Free Software Foundation, Inc.
+# Copyright 2015-2016 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -20,6 +20,11 @@
 
 fail=0
 
+# This test is susceptible to failure due to differences in
+# system load during the two test runs, so we'll mark it as
+# "expensive", making it less likely to be run by regular users.
+expensive_
+
 echo x > in || framework_failure_
 # We could use seq -s '' (avoiding the tr filter), but I
 # suspect some version of seq does not honor that option.
@@ -33,6 +38,6 @@ b10x_ms=$(user_time_ 1 grep -f re-10x in) || fail=1
 # Increasing the length of the regular expression by a factor
 # of 10 should cause no more than a 10x increase in duration.
 # However, we'll draw the line at 20x to avoid false-positives.
-expr $base_ms '<' $b10x_ms / 20 && fail=1
+returns_ 1 expr $base_ms '<' $b10x_ms / 20 || fail=1
 
 Exit $fail
diff --git a/reference/grep/tests/null-byte b/reference/grep/tests/null-byte
--- a/reference/grep/tests/null-byte
+++ b/reference/grep/tests/null-byte
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Test NUL bytes in patterns and data.
 
-# Copyright 2014-2015 Free Software Foundation, Inc.
+# Copyright 2014-2016 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -50,5 +50,19 @@ for left in '' a '#' '\0'; do
     done
   done
 done
+
+(echo xxx && yes yyy | sed 100000q && printf 'z\n\0') >in || framework_failure_
+echo xxx >exp || framework_failure_
+grep xxx in >out || fail=1
+compare exp out || fail=1
+
+printf '%s\n' xxx 'Binary file in matches' > exp || framework_failure_
+grep -E 'xxx|z' in >out || fail=1
+compare exp out || fail=1
+
+printf '%s\0' 'abcadc' >in || framework_failure_
+printf '%s\0' 'abc' 'adc' >exp || framework_failure_
+grep -oz 'a[^c]*c' in >out || fail=1
+compare exp out || fail=1
 
 Exit $fail
diff --git a/reference/grep/tests/pcre b/reference/grep/tests/pcre
--- a/reference/grep/tests/pcre
+++ b/reference/grep/tests/pcre
@@ -1,7 +1,7 @@
 #! /bin/sh
-# Ensure that with -P, \s matches a newline.
+# Simple PCRE tests.
 #
-# Copyright (C) 2001, 2006, 2009-2015 Free Software Foundation, Inc.
+# Copyright (C) 2001, 2006, 2009-2016 Free Software Foundation, Inc.
 #
 # Copying and distribution of this file, with or without modification,
 # are permitted in any medium without royalty provided the copyright
@@ -13,6 +13,8 @@ require_pcre_
 fail=0
 
 echo | grep -P '\s*$' || fail=1
-echo | grep -zP '\s$' || fail=1
+echo | returns_ 2 grep -zP '\s$' || fail=1
+echo '.ab' | returns_ 1 grep -Pwx ab || fail=1
+echo x | grep -Pz '[^a]' || fail=1
 
 Exit $fail
